In [1]:
from utils import layer_sizes,initialize_parameters,forward_propagation,backward_propagation,cost_function,update_parameters,predict_value,neural_network_model
import numpy as np
import matplotlib.pyplot as plt
# A library for data manipulation and analysis.
import pandas as pd

# Output of plotting commands is displayed inline within the Jupyter notebook.
%matplotlib inline
#for consistent result of random numbers
np.random.seed(3)

In [2]:
df = pd.read_csv("C:/pythonprojects/calculas_neural_network/datas/house_prices_train.csv")
X=df[['GrLivArea', 'OverallQual']]  #here we are selecting the ground living area  and overall quality based on which we are making the salesprice prediction
X

GrLivArea  OverallQual
0          1710            7
1          1262            6
2          1786            7
3          1717            7
4          2198            8
...         ...          ...
1455       1647            6
1456       2073            6
1457       2340            7
1458       1078            5
1459       1256            5

[1460 rows x 2 columns]

In [3]:
Y=df[['SalePrice']]
Y

SalePrice
0        208500
1        181500
2        223500
3        140000
4        250000
...         ...
1455     175000
1456     210000
1457     266500
1458     142125
1459     147500

[1460 rows x 1 columns]

In [4]:
#normalizing the data

X_norm = (X -np.mean(X,axis = 0)) / np.std(X,axis = 0)
X_norm
Y_norm = (Y -np.mean(Y,axis = 0)) / np.std(Y,axis = 0) 
X_norm

GrLivArea  OverallQual
0      0.370333     0.651479
1     -0.482512    -0.071836
2      0.515013     0.651479
3      0.383659     0.651479
4      1.299326     1.374795
...         ...          ...
1455   0.250402    -0.071836
1456   1.061367    -0.071836
1457   1.569647     0.651479
1458  -0.832788    -0.795151
1459  -0.493934    -0.795151

[1460 rows x 2 columns]

In [5]:
X_multiple = np.array(X_norm).T #so here we are converting the input data into numpy array having feature in row and samples of each feature as columns
X_multiple


array([[ 0.37033344, -0.48251191,  0.51501256, ...,  1.56964722,
        -0.83278768, -0.49393395],
       [ 0.65147924, -0.07183611,  0.65147924, ...,  0.65147924,
        -0.79515147, -0.79515147]], shape=(2, 1460))

In [6]:
Y_multiple = np.array(Y_norm).reshape((1,len(Y_norm)))  #the original sales value converted into numpy array having one row and multiple columns 
Y_multiple


array([[ 0.34727322,  0.00728832,  0.53615372, ...,  1.07761115,
        -0.48852299, -0.42084081]], shape=(1, 1460))

In [7]:
#defining the neural network structure


(n_x, n_y) = layer_sizes(X_multiple, Y_multiple)
print("The size of the input layer is: n_x = " + str(n_x))
print("The size of the output layer is: n_y = " + str(n_y))

The size of the input layer is: n_x = 2
The size of the output layer is: n_y = 1


In [8]:

parameters = initialize_parameters(n_x,n_y)
parameters

{'w': array([[0.17886285, 0.04365099]]), 'b': array([[0.]])}

In [9]:

Y_predicted = forward_propagation(X_multiple,parameters)
Y_predicted  #the predicted sale price initially

array([[ 0.0946766 , -0.08943917,  0.12055432, ...,  0.30918928,
        -0.18366392, -0.12305558]], shape=(1, 1460))

In [10]:
#calculating the cost function
cost_function(Y_predicted,Y_multiple)


np.float64(0.36030487446143783)

In [11]:

grads = backward_propagation(Y_predicted,Y_multiple,X_multiple)
grads



{'dw': array([[-0.50387627, -0.64126362]]), 'db': array([-1.46001932e-16])}

In [12]:

updated_paramters = update_parameters(parameters,grads,0.1)
updated_paramters



{'w': array([[0.22925047, 0.10777735]]), 'b': array([[1.46001932e-17]])}

In [13]:

final_parameters = neural_network_model(X_multiple,Y_multiple,30,0.1,print_cost=False)



In [15]:
X_pred = np.array([[1716,7],[1262,6,],[1786,7]]).T  #here we are passing the pair of samples of two features

Y_pred = predict_value(df[['GrLivArea', 'OverallQual']],df['SalePrice'],X_pred,final_parameters)
Y_pred


array([[220232.00328925, 161767.13716406, 224715.91303645]])